# Generated by Django 4.1.6 on 2023-02-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.IntegerField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('education', 'Education'), ('fiction', 'Fiction'), ('comics', 'Comics'), ('biography', 'Biography'), ('history', 'History')], default='education', max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('book_state', models.BooleanField(default=True)),
                ('book_defect', models.BooleanField(default=False)),
            ],
        ),
    ]
