# Generated by Django 4.1.6 on 2023-03-02 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_remove_book_id_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('subject', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Last Modify')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
