# Generated by Django 4.1.6 on 2023-03-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_bookcategory_alter_book_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
