# Generated by Django 4.1.6 on 2023-03-04 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0008_rename_category_bookcategory_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='studentID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BorrowBookSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(default=student.models.default_loan_date)),
                ('borrow_book_isbn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.book')),
                ('borrower_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentinformation')),
                ('borrower_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
