# Generated by Django 4.1.6 on 2023-03-05 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_remove_studentinformation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbooksession',
            name='borrower_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
