# Generated by Django 4.1.6 on 2023-03-06 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0010_alter_borrowbooksession_borrower_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_content', models.CharField(max_length=200)),
                ('complainant_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.book')),
            ],
        ),
    ]
