# Generated by Django 4.1.6 on 2023-03-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsession',
            name='complaint_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
