# Generated by Django 4.1.6 on 2023-03-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_complaintsession_complaint_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbooksession',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
